### ISSUE TITLE
HELP: Is the connection restarting?

### ISSUE THREAD

**Issue by Diegorro98** [mobizt/Firebase-ESP-Client#27]
Hi!
Today i was testing my code, that reads and writes in a Realtime database in Firebase, and I wrote in the plataformio.ini file the following:
`build_flags = -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG`
I saw how it works and the logs that are in the whole code, and I got surprised because each ~30 seconds, the following line appears: 
`[I][fb_ssl_client32.cpp:192] start_ssl_client(): WARNING: Use certificates for a more secure communication!`
My code is running perfectly, but this means that the ssl connection restarts? I don't thing that is a problem, but in [Firebase docs](https://firebase.google.com/docs/database/usage/optimize?hl=es-419#open-connections), they suggest to mantain the connection open, but maybe 30 seconds is the limit.

Another question I have is if I have to worry about the message `WARNING: Use certificates for a more secure communication!`. Should I use certificates for a more secure communication? How can I do it with Firebase?

And my las question: I've been supervising the usage of the realtime database, and this line:
`Firebase.RTDB.getInt(&fbdo, path.c_str())` (is executed twice per second and its purpose is to hear for changes in a path that contains an Int. Is there a more efficient way to do it?)
This line downloads about 2,4 MB per hour from the databse. Is that too much? This big quantity of bytes can be related to the problem of the restarting connection, because in Firebase docs says:
`These frequent, short-lived connections can actually add up to more connection costs, database load, and outbound bandwidth than live real-time connections to your database.`.

**Comment by mobizt** [comment]
The tcp session timeout of server is  approx 5 minutes  instead of 30 seconds

With the version prior to the latest update, he tcp session will not close and keep alive (open) to reuse the tcp session for speed up subsequence connection, this keep open until the connection was closed by server (approx. 5 minutes after last request).

With the latest version, the connection was keep alive and will close by client when 3 minutes timeout reached.

The connection will close manually when you call the following functions from Firebase Data object e.g. clear,  pauseFirebase, stopWiFiClient or you get the internal SSL client with getWiFiClient and call stop from it. 

For your question, if you are new to Firebase RTDB usage, please read the stream operation from the [Firebase doc](https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-streaming) or this library [doc](https://github.com/mobizt/Firebase-ESP-Client#stream-data).
You also can test the stream operation from [this example](https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Stream_Callback/Stream_Callback.ino).

The stream operation tcp session keeps open to waiting for event-data and not close by the library or server, except for the heartbeat data (keep-alive event data) was missed for 30 seconds, the stream connection will be reconnected.
