### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by topslave** [mobizt/Firebase-ESP-Client#379]
![Screen Shot 2022-08-27 at 18 16 15](https://user-images.githubusercontent.com/4818590/187036429-dc230c87-c759-4e25-a842-bcef8cf1d358.png)
I am trying to update these values in the lists for eg over time,  which template can I use in order to change the Boolean values.  I apologize for direct approach I have been working on this and it keeps giving me path error. 
many thanks

**Comment by mobizt** [comment]
**Just ask something**
If you have questions, use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) instead. 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Create minimal, clean and clear testing code that addressed the issue.
The third party libraries should be removed.
And post the testing code here.


**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**IDE and its version:**
 - Arduino, PlatformIO
 - Version [e.g. 1.8.9]

**ESP8266 Arduino Core SDK version**
 - Version [e.g. 2.5.1]

**Additional context**
Add any other context about the problem here.
