### ISSUE TITLE
TCP connection left open when trying to upload a file with invalid path name

### ISSUE THREAD

**Issue by lsalin** [mobizt/Firebase-ESP-Client#420]
When uploading files to storage I found that when I give an invalid file name the upload fails as expected (`File not found`) but after that all subsequent calls to access the RTDB or Firebase Storage fail with `http connection was used by other processes`. I did some digging around in the source code and it seems that fbdo->closeConnection() is not called when the filename is invalid. This seems to me to be a possible source for the issue, but I'm really not sure about that. When trying to reproduce, I found that if you only try to access storage it works as expected, but when my project also uses the real time database this issue occurs.

**To reproduce:**
This code (boilerplate not included) leaves HTTP connection open
```c++
void loop()
{
    if (Firebase.ready())
    {
        Serial.println("\nUpload file...\n");
        if (!Firebase.Storage.upload(&fbdo, STORAGE_BUCKET_ID, "/file_that_does_not_exist.abc" , mem_storage_type_flash, "xyz.abc", "text/text", fcsUploadCallback))
            Serial.println(fbdo.errorReason());
        if(!Firebase.RTDB.getInt(&fbdo, "fakeInt")) {
          Serial.println(fbdo.errorReason());
        };
    }
}
```

**Expected behavior**
Should fail gracefully and close all HTTP connections

**Comment by mobizt** [comment]
Due to the different APIs (end points), we don't know the priority of user works when the same FirebaseData object was use for many Google services then the TCP connection session will keep open to avoid new SSL handshake that takes time for every new connection under the same API end point.

Once the session created from first success connection, you must close the session by calling fbdo.clear() or fbdo.stopWiFiClient() yourself.
