### ISSUE TITLE
Is there a limit to the length of a string when it is uploaded to the RTDB?

### ISSUE THREAD

**Issue by ProyectoOVO** [mobizt/Firebase-ESP-Client#485]
Hello, im using the Firebase-ESP-Client lib, but before i was using the FirebaseESP32.h, the thing is that with the other library i was able to upload a VGA image (in base64) to the RTDB, but now i cannot, it doesnt arrive to firebase (the esp-32cam has no problem encrypting in base64 a vga image), but with the same function i can upload a QVGA image, so the function works. I was wondering if is there a limitation on the bytes or length when using strings? Because is strange, i dont think is a firebase console limitation because as i said i was able to upload the string without problem with the other lib.

**Comment by mobizt** [comment]
Conversion large image data to base64 string in this low memory device is not efficient and may limited due to Heap fragmentation.

I recommend [Blob](https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Blob/Blob.ino) and [Files](https://github.com/mobizt/Firebase-ESP-Client/tree/main/examples/RTDB/File) that already implemented in this library.

The BLOB and File will be converted to base64 encoded string on the fly when you store (upload) to RTDB database and converted from base64 string to BLOB and File when restore (download) from RTDB database.

In your case, you can use send image data directly via Blob function or save it to file and send it later via File functions.
