### ISSUE TITLE
setFloat stops working after 3.1.6

### ISSUE THREAD

**Issue by buccaneer-jak** [mobizt/Firebase-ESP-Client#506]
**Describe the bug**
Arduino IDE 2.0.4: 
Client Library for ESP8266 and ESP32: 
Library 3.1.6 setFloat works correctly, updates the db and returns fbdo.dataType() float. 
With 3.1.7 and higher versions, setFloat returns TRUE but doesn't update the database and fbdo.dataType() = int.

Also none of the Firebase ESP32 Client versions work with setFloat() for the same reason.

**To Reproduce**
    if (Firebase.RTDB.setFloat(&fbdo, "test/float", 0.01 + random(0,100))){
      Serial.println("PASSED");
      Serial.println("PATH: " + fbdo.dataPath());
      Serial.println("TYPE: " + fbdo.dataType())
}

**Expected behaviour**
db should update.

**Screenshots**

**IDE and its version:**
 - Arduino, 
 - Version 2.0.4

**ESP32-C3 revision 4**
 - Version 
 - esptool.py v4.2.1

**Additional context**

**Comment by mobizt** [comment]
I confirm that there is no such issue and library was intensively tested for years.

The library version you mentioned is outdated for years and you should update.

The issue you get is because you are trying to update the library through Arduino's Library Manager with the manually install library using zip file. You can read the compilation issue caused by Arduino Installation system [here](https://github.com/mobizt/Firebase-ESP-Client#important-note-for-manual-installation-in-arduino-ide).

You should remove all Firebase libraries in Arduino libraries folder and install new library using Library Manager only.
