### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by usrrsr** [mobizt/Firebase-ESP-Client#51]
I am using firebase realtime database and example "AutomaticPlantWatering.ino". Compilation gives  following error 

sketch\AutomaticPlantWatering.ino.cpp.o:(.literal._Z5setupv+0x88): undefined reference to `bool FB_RTDB::set<FirebaseJsonArray>(FirebaseData*, char const*, FirebaseJsonArray)'
sketch\AutomaticPlantWatering.ino.cpp.o: In function `setup()':

Also when i want to use following function 
FirebaseData fbdo1;
FirebaseData fbdo2;
Firebase.RTDB.set(&fbdo2, path + "/Dimmer" + j + "Speed", 0);

program throw following error
no matching function for call to 'FB_RTDB::set(FirebaseData*, StringSumHelper&, int)'

Please help and at least add one example to set and read a variable from realtime database

**Comment by mobizt** [comment]
1. Due to missing the & operator, please edit this line 217 from
https://github.com/mobizt/Firebase-ESP-Client/blob/52e29812b23357d354fa51d866af62027c2126f3/examples/RTDB/AutomaticPlantWatering/AutomaticPlantWatering.ino#L217
to 
**Firebase.RTDB.set(&fbdo2, Path.c_str(), &scheduleConfig);**

2. Don't join the string with + operator. It's not give the string literal or pointer to const char as accepted by the second parameter of that function. You should do like this.

```cpp
String node = path + "/Dimmer" + String(j) + "Speed";
Firebase.RTDB.set(&fbdo2, node.c_str(), 0);
```
