### ISSUE TITLE
incomplete type std::string for strings used in library (_host , _CaCert )

### ISSUE THREAD

**Issue by AashayaDesigns** [mobizt/Firebase-ESP-Client#66]
C:\Users\User\Documents\Arduino\libraries\arduino_107156\src/wcs/esp8266/FB_HTTPClient.h:109:15: error: field '_host' has incomplete type 'std::string' {aka 'std::__cxx11::basic_string<char>'}
  109 |   std::string _host = "";

Error when compiling the files itself.

**To Reproduce**
1. Update to arduino core 3.0.0
2. Open any example from library
2. Compile

**Expected behavior**
Was compiling flawlessly previously in Arduino core 2.7.4

**IDE and its version:**
 - Arduino, 1.8.14

**ESP8266 Arduino Core SDK version**
 - 3.0.0

**Comment by mobizt** [comment]
This is due to the GCC 10 compiler error used in ESP8266 Arduino Core SDK 3.0.0 which you're using.

The library updated to [v2.2.0](https://github.com/mobizt/Firebase-ESP-Client/releases/tag/v2.2.0) to support this new SDK. 

Please update.

Please read [this](https://github.com/mobizt/Firebase-ESP-Client#important-information) as it affected to your free memory.
